@success = true

task :default => [:run_tests]

task :run_tests, [:environment, :browser, :tags, :feature, :scenario, :driverPath] do |t, args|
	cucumberStatement = 'cucumber ENVIRONMENT=' + args[:environment] + ' BROWSER=' + args[:browser]
	if (!args[:tags].nil? && !args[:tags].empty?)
		splitTags = args[:tags].split ' '
		splitTags.each do |singleTag|
			cucumberStatement += ' --tags @' + singleTag
		end
	elsif (!args[:feature].nil? && !args[:feature].empty?)
		cucumberStatement += ' features/' + args[:feature] + '.feature'
	elsif (!args[:scenario].nil? && !args[:scenario].empty?)
		cucumberStatement += ' features --name "' + args[:scenario] + '"'
	end
	if (!args[:driverPath].nil? && !args[:driverPath].empty?)
		cucumberStatement += 'DRIVERPATH = ' + args[:driverPath]
	end
	puts cucumberStatement
	sh(cucumberStatement) do |success, _exit_code |
		@success &= success
	end
end

task :run_dev_chrome_homepage do
	cucumberStatement = 'cucumber ENVIRONMENT=dev BROWSER=chrome --require features features/homepage.feature'
	sh(cucumberStatement) do |success, _exit_code |
		@success &= success
	end
end

task :run_tests_sauce, [:environment, :platform, :browser, :browser_version, :tags, :feature, :scenario] do |t, args|
	cucumberStatement = 'cucumber ENVIRONMENT=' + args[:environment]  
	cucumberStatement +=' SAUCE=true PLATFORM=\'' + args[:platform] + '\' BROWSER=' + args[:browser] + ' BROWSER_VERSION=' + args[:browser_version] 
	if (!args[:tags].nil? && !args[:tags].empty?)
		splitTags = args[:tags].split ' '
		splitTags.each do |singleTag|
			cucumberStatement += ' --tags @' + singleTag
		end
	elsif (!args[:feature].nil? && !args[:feature].empty?)
		cucumberStatement += ' features/' + args[:feature] + '.feature'
	elsif (!args[:scenario].nil? && !args[:scenario].empty?)
		cucumberStatement += ' features --name "' + args[:scenario] + '"'
	end
	puts cucumberStatement
	sh(cucumberStatement) do |success, _exit_code |
		@success &= success
	end
end
